// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fryjsygqdvcuaabjerag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyeWpzeWdxZHZjdWFhYmplcmFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNTkwOTUsImV4cCI6MjA2NDczNTA5NX0.aZEVYE6IDjh_0LY9lETfAkHKx1d7xY0Sk2TLi-FUKds";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);